import VideoCard from '@/components/VideoCard';
import { getCatalogVideos } from '@/lib/catalog';
import '../../../pages/Pages.css';

export const runtime = 'edge';

export async function generateMetadata() {
  const hasEvidence = getCatalogVideos().some((video) => Number.isFinite(video.viewGrowth7d));
  return {
    title: 'Fastest Rising This Week — NICEVX',
    description: 'Videos ranked from measured view changes between factual daily snapshots.',
    alternates: { canonical: 'https://www.nicevx.com/trends/weekly' },
    robots: { index: hasEvidence, follow: true },
  };
}

export default function WeeklyTrendsPage() {
  const rising = getCatalogVideos().filter((video) => Number.isFinite(video.viewGrowth7d) && video.viewGrowth7d > 0).sort((a, b) => b.viewGrowth7d - a.viewGrowth7d).slice(0, 36);
  return <main className="page-wrapper collection-page"><h1>Fastest Rising This Week</h1><p className="collection-lead">This report publishes only measured view growth. A trend is never inferred from a title, generated by AI, or displayed before two snapshots exist.</p>{rising.length ? <div className="video-grid">{rising.map((video) => <VideoCard key={video.id} video={video} />)}</div> : <div className="empty-block"><p>Waiting for another daily snapshot before publishing trend claims.</p></div>}</main>;
}
